format = '[$all](bold purple)'
[cmd_duration]
show_notifications = true
[directory]
style = "bold bright-blue"
read_only = " "
[docker_context]
symbol = " "
disabled = true
[gcloud]
disabled = true
[git_branch]
symbol = " "
style = "bold white"
[git_status]
style = "bold bright-red"
[hostname]
style = "bold bright-green"
[package]
symbol = " "
disabled = true
[python]
symbol = " "
style = "bold cyan"
[username]
style_user = "bold bright-green"
