model = "gpt-5.1-codex-max"
model_verbosity = "high"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
hide_agent_reasoning = false

[features]
web_search_request = true

[sandbox_workspace_write]
network_access = true

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
# http_headers = { "CONTEXT7_API_KEY" = "YOUR_API_KEY" }
[mcp_servers.grep]
url = "https://mcp.grep.app"
